config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'trunk_lines#index'
  resources :trunk_lines do |variable|
    get :autocomplete_trunk_line_full_address, :on => :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dist.rb
class Dist < ApplicationRecord
end

app/models/trunk_line.rb
class TrunkLine < ApplicationRecord
  before_validation :reformat
  after_validation :format_full_address

  geocoded_by :full_address
  before_save :geocode

  def self.search(address)
    if address
      self.where("full_address LIKE ?","%#{address}%")
    else
      all
    end
  end


  protected
  def reformat
    self.respond_area = self.respond_area.delete(" ")
    self.address = self.address.delete(" ").delete("\r\n")
    self.dist = self.dist.delete(" ").delete(" ").delete("\r\n")
    self.vil = self.vil.delete(" ").delete(" ").delete("\r\n")
    self.around_time = self.around_time.delete(" ")
    self.recover_date =self.recover_date.delete(" ")
  end


  def format_full_address
    rex = get_address_regex
    full_address = self.dist + self.vil + self.address

    rex.each do |item|
      full_address.gsub!(item[:re],item[:rep])
    end

    full_address = process_end_address(full_address)

    self.full_address = full_address.strip
  end

  def process_end_address(addr)
    if (addr[-3..-2] == " 前" || addr[-3..-2] == "前 " || addr[-2] == "前" || addr[-1] == "前")
      addr.gsub!(/(前)/,"")
    end
    if (addr[-3..-2] == " 旁" || addr[-3..-2] == "旁 " || addr[-2] == "旁" || addr[-1] == "旁")
      addr.gsub!(/(旁)/,"")
    end
    addr
  end

  def get_address_regex
    rex = []
    rex.push({re: /(（|）|側門|對面|門口|迴轉|收至|結束|終站|貯坑|大門前|關音樂|沿路收|\(|\)|\+)/, rep: " "})
  	rex.push({re: /(前$|旁$)/, rep: " "})
  	rex.push({re: /(號前)/, rep: "號"})
  	rex.push({re: /(站旁)/, rep: "站"})
  	rex.push({re: /(與路|路口|路路口|路前|路旁|路底)/, rep: "路"})
  	rex.push({re: /(與街|街口|街街口|街前|街旁|街底)/, rep: "街"})
  	rex.push({re: /(與巷|巷口|巷巷口|巷前|巷旁|巷尾|巷底)/, rep: "巷"})
  	rex.push({re: /與弄|弄口|弄弄口|弄前|弄旁|弄底/, rep: "弄"})
    rex.push({re: /(三民西區|三民東區)/, rep: "三民區"})
  	rex.push({re: /(南鳳山區|北鳳山區)/, rep: "鳳山區"})
  	rex
  end
end

app/models/village.rb
class Village < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trunk_lines_controller.rb
class TrunkLinesController < ApplicationController
  autocomplete :trunk_line, :full_address
  def index
    @search  = params[:search] || {}
    if (@search[:range] == "1")
      @trunklines = TrunkLine.near(result,0.5, units: "km")
    else
      @trunklines = TrunkLine.search(@search[:address])
    end

    @hash = Gmaps4rails.build_markers(@trunklines) do |trunkline, marker|
      marker.lat trunkline.latitude
      marker.lng trunkline.longitude
      marker.infowindow render_to_string(:partial=> 'info_box', :locals => { :trunkline => trunkline})
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trunk_lines_helper.rb
module TrunkLinesHelper
  def render_check_status(status)
    status = status || "0"
    if status == "0"
      false
    else
      true
    end
  end
end

app/views/common/_map.html.erb
<div class="row">
  <div id="map" style='width: 100%; height: 600px;'></div>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">高雄市垃圾車</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GarbageTruck</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?v=3.23&key=<%= ENV['google_api_key'] %>"</script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  </head>
  <body>
    <div class="container">
      <%= render "common/navbar" %>
      <%= yield %>
      <%= render "common/map" %>
    </div>
  </body>
</html>

app/views/trunk_lines/_info_box.html.erb
<table class="table">
  <thead>
    <th></th>
    <th></th>
  </thead>
  <tbody>

  <tr>
    <td class="info">停留時間</td>
    <td class="active"><%= trunkline.around_time %></td>
  </tr>
  <tr>
    <td class="success">回收日(星期)</td>
    <td class="active"><%= trunkline.recover_date %></td>
  </tr>
  <tr>
    <td class="warning">停留地點</td>
    <td class="active"><%= trunkline.full_address %></td>
  </tr>

  </tbody>
</table>

app/views/trunk_lines/index.html.erb
<div class="row">
  <%= simple_form_for :search ,url: trunk_lines_path , :method => :get do |f| %>
    <div class="col-md-8">
      <%= f.input :address, url: autocomplete_trunk_line_full_address_trunk_lines_path, :as => :autocomplete, label: false, placeholder: '地址' ,input_html: { value: @search[:address] } ,:autofocus => true %>
    </div>
    <div class="col-md-2">
      <%= f.input :range, as: :boolean,label: "搜尋地址附近500公尺", input_html: { :checked => render_check_status(@search[:range]) } %>
    </div>
    <div class="col-md-2">
      <%= f.submit "搜尋", class: "btn btn-primary pull-right" ,data:{disable_with: "搜尋中"}, name:nil %>

    </div>
  <% end %>
</div>

<script src="http://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
      getLocation();
      var userLocation = {lat:22.684465279202286, lng:120.31153561257864};

      function initMap() {
          handler = Gmaps.build('Google');
          handler.buildMap({
                  provider: {
                      disableDefaultUI: true,
                      zoom: 15,
                      center: { lat: userLocation.lat, lng: userLocation.lng }
                  },
                  internal: {
                      id: 'map'
                  }
              },
              function() {
                  markers = handler.addMarkers(<%= raw @hash.to_json %>);
                  handler.bounds.extendWith(markers);
                  // handler.fitMapToBounds();
              });
      }


      function getLocation() {
          if (navigator.geolocation) {
              navigator.geolocation.getCurrentPosition(showPosition,showError);
          } else {
               console.log("Geolocation is not supported by this browser.");
          }

      }

      function showPosition(position) {
          userLocation.lat = position.coords.latitude;
          userLocation.lng = position.coords.longitude;
          initMap();
      }
      function showError(error){
        if (error){
          initMap();
        }
      }
  });



</script>